version: '3.8'
services:
  account-service-db:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account-service
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d account-service" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - tarificator-network

  client-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18001:18001"
    depends_on:
      - account-service-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://account-service-db/account-service
    networks:
      - tarificator-network
networks:
  tarificator-network:
    external: true
